// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    return AwesomeStage.Sprite = (function() {

      function Sprite() {}

      return Sprite;

    })();
  });

}).call(this);
