// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    var ALE;
    ALE = (function() {

      function ALE(width, height) {
        this.addToLayer = __bind(this.addToLayer, this);
        this.stage = new Kinetic.Stage({
          container: "container",
          width: width,
          height: height
        });
        this.layers = [];
        ALE.prototype.__instance = this;
      }

      ALE.prototype.addToLayer = function(layer, object) {
        if (this.layers[layer] == null) {
          this.layers[layer] = new Kinetic.Layer();
          this.stage.add(this.layers[layer]);
        }
        return this.layers[layer].add(object);
      };

      return ALE;

    })();
    window.ALE = ALE;
    return ALE.prototype.instance = function() {
      if (ALE.prototype.__instance == null) {
        ALE.prototype.__instance = new ALE(800, 600);
      }
      return ALE.prototype.__instance;
    };
  });

}).call(this);
