// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  YUI().use(function(Y) {
    var ALE;
    ALE = (function() {

      function ALE(width, height) {
        this.addToLayer = __bind(this.addToLayer, this);

        this.add = __bind(this.add, this);

        this.checkLayer = __bind(this.checkLayer, this);
        this.stage = new Kinetic.Stage({
          container: "container",
          width: width,
          height: height
        });
        this.layers = [];
        ALE.prototype.__instance = this;
      }

      ALE.prototype.checkLayer = function(layer) {
        if (this.layers[layer] == null) {
          this.layers[layer] = new Kinetic.Layer();
          return this.stage.add(this.layers[layer]);
        }
      };

      ALE.prototype.add = function(object, options) {
        options = Y.merge({
          draggable: true
        }, options);
        object.getKNode().setDraggable(options["draggable"]);
        return this.addToLayer(object.getLayer(), object.getKNode());
      };

      ALE.prototype.addToLayer = function(layer, object) {
        this.checkLayer(layer);
        return this.layers[layer].add(object);
      };

      return ALE;

    })();
    window.ALE = ALE;
    return ALE.prototype.instance = function() {
      if (ALE.prototype.__instance == null) {
        ALE.prototype.__instance = new ALE(800, 600);
      }
      return ALE.prototype.__instance;
    };
  });

}).call(this);
