// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    var Node;
    return Node = (function() {
      var NOT_IMPLEMENTED_EXCEPTION;

      function Node() {}

      NOT_IMPLEMENTED_EXCEPTION = "Not implemented yet.";

      Node.prototype.load = function(func) {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.getLayer = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.getKNode = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      return Node;

    })();
  });

}).call(this);
