// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    return ALE.Node = (function() {
      var NOT_IMPLEMENTED_EXCEPTION;

      function Node() {}

      NOT_IMPLEMENTED_EXCEPTION = "Not implemented yet.";

      Node.prototype.load = function(func) {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.getLayer = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.getKNode = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.clone = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.update = function(prototype) {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.getPreview = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.getName = function() {
        throw NOT_IMPLEMENTED_EXCEPTION;
      };

      Node.prototype.setParent = function(parent) {
        return this._parent = parent;
      };

      Node.prototype.getParent = function() {
        return this._parent;
      };

      return Node;

    })();
  });

}).call(this);
