// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    return ALE.Template = (function() {

      function Template(prototype) {
        this._prototype = prototype;
        this._clones = [];
      }

      Template.prototype.getPlaceholder = function() {
        if (this._placeholder == null) {
          this.setPlaceholder(jQuery("<a>" + this._prototype.getName() + "</a>"));
        }
        return this._placeholder;
      };

      Template.prototype.setPlaceholder = function(placeholder) {
        this._placeholder = placeholder;
        this._placeholder.data("template", this);
        return this._placeholder.draggable({
          revert: true,
          helper: "clone"
        });
      };

      Template.prototype.setDefaultAnimation = function(anim) {
        return this._defaultAnimation = anim;
      };

      Template.prototype.getDefaultAnimation = function() {
        return this._defaultAnimation;
      };

      Template.prototype.clone = function() {
        var _clone;
        _clone = this._prototype.clone();
        this._clones.push(_clone);
        _clone.setParent(this);
        return _clone;
      };

      Template.prototype.prototypeChanged = function() {
        var _clone, _i, _len, _ref, _results;
        _ref = this._clones;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          _clone = _ref[_i];
          _results.push(_clone.update(this._prototype));
        }
        return _results;
      };

      return Template;

    })();
  });

}).call(this);
